### ISSUE TITLE
Не удаётся скачать музыку из вк

### ISSUE THREAD

**Issue by Frodox** [HaCk3Dq/vktotg#13]
```
python3 ./vktotg.py                                                                     ✭
Do you want to leave the local files? [N/y] y
First, log in to vk.com
Enter login: sy***
Enter password: 
Traceback (most recent call last):
  File "./vktotg.py", line 153, in <module>
    main()
  File "./vktotg.py", line 117, in main
    audios = vkaudio.get(user_id)
  File "/usr/lib/python3.5/site-packages/vk_api/audio.py", line 90, in get
    return list(self.get_iter(owner_id, album_id))
  File "/usr/lib/python3.5/site-packages/vk_api/audio.py", line 73, in get_iter
    tracks = scrap_data(response.text, self.user_id)
  File "/usr/lib/python3.5/site-packages/vk_api/audio.py", line 201, in scrap_data
    duration = int(audio.select_one('.ai_dur')['data-dur'])
TypeError: 'NoneType' object is not subscriptable

```

**Comment by HaCk3Dq** [comment]
Хм, возможно снова что-то поменяли
Гляну скоро
