### ISSUE TITLE
Downloading porblem

### ISSUE THREAD

**Issue by ph0bo** [HaCk3Dq/vktotg#8]
Hi!
I'm trying to use .exe file from windows to download all my music to the local folder and I am getting this error:
`C:\vktotg-master>vktotg.exe _my_vk_userid_
Do you want to leave the local files? [N/y] y
First, log in to vk.com
Enter login: ---
Enter password: ---
Downloading audios from _my_vk_userid_
Traceback (most recent call last):
  File "vktotg.py", line 201, in <module>
    print()
  File "vktotg.py", line 135, in main
    folderName = 'Music '
  File "vktotg.py", line 120, in auth_tg

  File "site-packages\telethon\telegram_bare_client.py", line 188, in connect
  File "site-packages\telethon\network\mtproto_sender.py", line 49, in connect
  File "site-packages\telethon\network\connection.py", line 79, in connect
  File "site-packages\telethon\extensions\tcp_client.py", line 49, in connect
socket.timeout: timed out
[1720] Failed to execute script vktotg`

What is going wrong? Do I nevertheless need to login into Telegram?

**Comment by HaCk3Dq** [comment]
Hi, will resolve it in a few days.
